version: '3.8'

services:
  backend:
    build:
      context: ./DEMOShoesSizeTag
      dockerfile: Dockerfile
    image: gitzno/shoesize-api:latest 
    container_name: shoesize_api
    ports:
      - "5144:8080"
    environment:
      - Gemini__ApiKey=${GEMINI_API_KEY}
    networks:
      - app-network

  frontend:
    build:
      context: ./shoe-demo
      dockerfile: Dockerfile
    image: gitzno/shoesize-frontend:latest
    container_name: shoesize_frontend
    ports:
      - "9901:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge